# Generated by Django 5.2.5 on 2025-09-26 14:54

from django.db import migrations

def create_default_locations(apps, schema_editor):
    Location = apps.get_model("pantry", "Location")
    for loc_name in ["Fridge", "Freezer", "Cabinets"]:
        Location.objects.get_or_create(name=loc_name)

class Migration(migrations.Migration):

    dependencies = [
        ('pantry', '0005_groceryitem_user_alter_pantryitem_location'),
    ]

    operations = [
        migrations.RunPython(create_default_locations),
    ]
