# Generated by Django 5.2.5 on 2025-09-29 20:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pantry', '0006_create_default_locations'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pantryitem',
            name='location',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='items', to='pantry.location'),
        ),
    ]
